In [3]:
import pandas as pd
import numpy as np
from itertools import repeat
from urllib.request import urlopen
import ssl
import time
import urllib.request

In [4]:
aad = pd.read_csv(f'/Users/calebsmith/Library/Mobile Documents/com~apple~CloudDocs/Documents/What If/Hoops/Teams/Andre_and_Deandre.csv')
aad['Team'] = 'Andre and Deandre'
aad

,Name,GP,GS,Min,Pts,FGM,FGA,3PM,3PA,FTM,...,Stl,Blk,PF,2PM,2PA,2P%,3P%,FG%,eFG,Team
0,15-16 DeAndre Jordan,82,82,2676,1198,538,786,1,3,121,...,48,174,181,537,783,68.582375,33.333333,68.447837,68.511450,Andre and Deandre
1,95-96 Dennis Rodman,82,77,2169,437,192,390,5,33,48,...,49,28,184,187,357,52.380952,15.151515,49.230769,49.871795,Andre and Deandre
2,18-19 LeBron James,82,54,1996,1355,547,1124,102,305,159,...,73,29,94,445,819,54.334554,33.442623,48.665480,53.202847,Andre and Deandre
3,22-23 Stephen Curry,82,61,1992,1523,527,1166,254,657,215,...,63,19,104,273,509,53.634578,38.660578,45.197256,56.089194,Andre and Deandre
4,93-94 Nate McMillan,82,79,1962,419,171,437,47,136,30,...,241,25,186,124,301,41.196013,34.558824,39.130435,44.508009,Andre and Deandre
5,20-21 LeBron James,82,27,1751,1307,496,997,124,350,191,...,55,28,62,372,647,57.496136,35.428571,49.749248,55.967904,Andre and Deandre
6,17-18 Stephen Curry,82,21,1680,1389,460,925,238,530,231,...,91,8,91,222,395,56.202532,44.905660,49.729730,62.594595,Andre and Deandre
7,94-95 Dennis Rodman,82,5,1621,413,174,322,0,6,65,...,40,23,116,174,316,55.063291,0.000000,54.037267,54.037267,Andre and Deandre
8,95-96 Nate McMillan,82,3,1310,273,97,269,45,124,34,...,90,22,127,52,145,35.862069,36.290323,36.059480,44.423792,Andre and Deandre
9,12-13 Andre Drummond,82,0,1306,543,252,430,1,3,38,...,83,103,118,251,427,58.782201,33.333333,58.604651,58.720930,Andre and Deandre
10,96-97 Kevin Gamble,82,1,981,290,107,289,52,117,24,...,39,21,61,55,172,31.976744,44.444444,37.024221,46.020761,Andre and Deandre
11,13-14 Gal Mekel,82,0,338,79,33,117,3,27,10,...,5,1,28,30,90,33.333333,11.111111,28.205128,29.487179,Andre and Deandre

In [5]:
aotc2 = pd.read_csv(f'/Users/calebsmith/Library/Mobile Documents/com~apple~CloudDocs/Documents/What If/Hoops/Teams/aotc2.csv')
aotc2['Team'] = 'Attack of the Clones: Part 2'
aotc2

,Name,GP,GS,Min,Pts,FGM,FGA,3PM,3PA,FTM,...,Stl,Blk,PF,2PM,2PA,2P%,3P%,FG%,eFG,Team
0,21-22 Christian Wood,82,63,2131,1133,440,955,110,334,143,...,61,47,168,330,621,53.140097,32.934132,46.073298,51.832461,Attack of the Clones: Part 2
1,16-17 Nikola Jokic,82,52,2095,1179,490,905,31,135,168,...,66,36,161,459,770,59.610390,22.962963,54.143646,55.856354,Attack of the Clones: Part 2
2,22-23 Stephen Curry,82,48,1989,1598,548,1146,265,615,237,...,58,14,96,283,531,53.295669,43.089431,47.818499,59.380454,Attack of the Clones: Part 2
3,93-94 Nate McMillan,82,60,1926,404,159,412,44,136,42,...,231,16,165,115,276,41.666667,32.352941,38.592233,43.932039,Attack of the Clones: Part 2
4,21-22 Mitchell Robinson,82,45,1885,702,320,441,0,6,62,...,64,102,182,320,435,73.563218,0.000000,72.562358,72.562358,Attack of the Clones: Part 2
5,19-20 Mitchell Robinson,82,37,1800,790,361,499,1,1,67,...,84,129,208,360,498,72.289157,100.000000,72.344689,72.444890,Attack of the Clones: Part 2
6,21-22 Domantas Sabonis,82,30,1685,888,348,599,40,104,152,...,54,12,126,308,495,62.222222,38.461538,58.096828,61.435726,Attack of the Clones: Part 2
7,17-18 Stephen Curry,82,34,1673,1372,482,987,234,541,174,...,96,7,74,248,446,55.605381,43.253235,48.834853,60.688956,Attack of the Clones: Part 2
8,20-21 Christian Wood,82,19,1544,918,375,731,87,221,81,...,43,58,93,288,510,56.470588,39.366516,51.299590,57.250342,Attack of the Clones: Part 2
9,95-96 Nate McMillan,82,22,1298,267,94,263,43,121,36,...,118,21,136,51,142,35.915493,35.537190,35.741445,43.916350,Attack of the Clones: Part 2
10,05-06 DerMarr Johnson,82,0,943,330,114,278,50,137,52,...,41,24,73,64,141,45.390071,36.496350,41.007194,50.000000,Attack of the Clones: Part 2
11,21-22 Lance Stephenson,82,0,768,339,135,305,29,81,40,...,40,3,61,106,224,47.321429,35.802469,44.262295,49.016393,Attack of the Clones: Part 2

In [6]:
iwi = pd.read_csv(f'/Users/calebsmith/Library/Mobile Documents/com~apple~CloudDocs/Documents/What If/Hoops/Teams/IWI.csv')
iwi['Team'] = 'I WANT IGUODALA'
iwi

,Name,GP,GS,Min,Pts,FGM,FGA,3PM,3PA,FTM,...,Stl,Blk,PF,2PM,2PA,2P%,3P%,FG%,eFG,Team
0,15-16 DeAndre Jordan,82,82,2725,1137,490,715,0,3,157,...,69,152,224,490,712,68.820225,0.000000,68.531469,68.531469,I WANT IGUODALA
1,22-23 Stephen Curry,82,44,2004,1512,534,1145,267,640,177,...,66,11,112,267,505,52.871287,41.718750,46.637555,58.296943,I WANT IGUODALA
2,18-19 LeBron James,82,51,1995,1397,541,1122,98,302,217,...,93,29,98,443,820,54.024390,32.450331,48.217469,52.584670,I WANT IGUODALA
3,93-94 Nate McMillan,82,82,1963,474,186,417,47,122,55,...,280,19,187,139,295,47.118644,38.524590,44.604317,50.239808,I WANT IGUODALA
4,21-22 Mitchell Robinson,82,53,1906,632,290,391,0,0,52,...,82,120,170,290,391,74.168798,0.000000,74.168798,74.168798,I WANT IGUODALA
5,19-20 Mitchell Robinson,82,29,1820,795,361,505,0,0,73,...,99,127,225,361,505,71.485149,0.000000,71.485149,71.485149,I WANT IGUODALA
6,20-21 LeBron James,82,30,1781,1271,496,1025,107,320,172,...,70,31,61,389,705,55.177305,33.437500,48.390244,53.609756,I WANT IGUODALA
7,17-18 Stephen Curry,82,38,1690,1308,454,950,225,540,175,...,97,7,118,229,410,55.853659,41.666667,47.789474,59.631579,I WANT IGUODALA
8,95-96 Nate McMillan,82,0,1302,313,112,276,49,126,40,...,119,22,123,63,150,42.000000,38.888889,40.579710,49.456522,I WANT IGUODALA
9,06-07 Reggie Evans,82,0,1164,399,163,294,0,1,73,...,57,21,118,163,293,55.631399,0.000000,55.442177,55.442177,I WANT IGUODALA
10,12-13 Luke Walton,80,1,926,179,72,214,17,75,18,...,51,5,92,55,139,39.568345,22.666667,33.644860,37.616822,I WANT IGUODALA
11,19-20 Andre Iguodala,82,0,504,125,51,124,15,64,8,...,20,27,23,36,60,60.000000,23.437500,41.129032,47.177419,I WANT IGUODALA

In [7]:
mj = pd.read_csv(f'/Users/calebsmith/Library/Mobile Documents/com~apple~CloudDocs/Documents/What If/Hoops/Teams/MJ.csv')
mj['Team'] = 'Can Michael Win a WIS Championship?'
mj

,Name,GP,GS,Min,Pts,FGM,FGA,3PM,3PA,FTM,...,Stl,Blk,PF,2PM,2PA,2P%,3P%,FG%,eFG,Team
0,87-88 Michael Jordan,82,82,3419,2775,1127,2209,5,69,516,...,307,151,218,1122,2140,52.429907,7.246377,51.018560,51.131734,Can Michael Win a WIS Championship?
1,97-98 Dennis Rodman,82,81,2936,431,185,431,4,17,57,...,75,17,184,181,414,43.719807,23.529412,42.923434,43.387471,Can Michael Win a WIS Championship?
2,09-10 Dwight Howard,82,80,2909,1696,701,1108,1,12,293,...,115,193,244,700,1096,63.868613,8.333333,63.267148,63.312274,Can Michael Win a WIS Championship?
3,07-08 Steve Nash,82,80,2832,1464,523,1069,200,413,218,...,67,8,111,323,656,49.237805,48.426150,48.924228,58.278765,Can Michael Win a WIS Championship?
4,14-15 Kyle Korver,82,65,2474,881,286,642,216,473,93,...,78,40,106,70,169,41.420118,45.665962,44.548287,61.370717,Can Michael Win a WIS Championship?
5,22-23 Sam Hauser,82,15,1323,470,157,365,117,296,39,...,42,15,81,40,69,57.971014,39.527027,43.013699,59.041096,Can Michael Win a WIS Championship?
6,21-22 Tyrese Haliburton,82,0,980,448,167,347,63,140,51,...,47,10,35,104,207,50.241546,45.000000,48.126801,57.204611,Can Michael Win a WIS Championship?
7,18-19 Tyson Chandler,82,1,899,192,82,143,0,2,28,...,22,21,91,82,141,58.156028,0.000000,57.342657,57.342657,Can Michael Win a WIS Championship?
8,16-17 JaVale McGee,82,2,761,530,240,359,0,4,50,...,27,71,95,240,355,67.605634,0.000000,66.852368,66.852368,Can Michael Win a WIS Championship?
9,10-11 Luke Walton,81,2,585,103,35,136,11,50,22,...,22,3,51,24,86,27.906977,22.000000,25.735294,29.779412,Can Michael Win a WIS Championship?
10,13-14 Gal Mekel,80,2,369,86,34,119,6,27,12,...,3,0,30,28,92,30.434783,22.222222,28.571429,31.092437,Can Michael Win a WIS Championship?
11,17-18 Kawhi Leonard,72,0,224,114,46,134,6,45,16,...,15,6,8,40,89,44.943820,13.333333,34.328358,36.567164,Can Michael Win a WIS Championship?

In [8]:
tcc = pd.read_csv(f'/Users/calebsmith/Library/Mobile Documents/com~apple~CloudDocs/Documents/What If/Hoops/Teams/TCC.csv')
tcc['Team'] = 'Tyson Chicken Curry'
tcc

,Name,GP,GS,Min,Pts,FGM,FGA,3PM,3PA,FTM,...,Stl,Blk,PF,2PM,2PA,2P%,3P%,FG%,eFG,Team
0,67-68 Wilt Chamberlain,82,82,3934,1928,871,1445,1,4,185,...,140,318,146,870,1441,60.374740,25.000000,60.276817,60.311419,Tyson Chicken Curry
1,97-98 Dennis Rodman,82,81,2905,450,190,437,3,30,67,...,53,21,189,187,407,45.945946,10.000000,43.478261,43.821510,Tyson Chicken Curry
2,22-23 Stephen Curry,82,49,1986,1635,577,1186,270,629,211,...,57,25,130,307,557,55.116697,42.925278,48.650927,60.033727,Tyson Chicken Curry
3,18-19 LeBron James,82,50,1969,1426,563,1152,108,316,192,...,72,31,78,455,836,54.425837,34.177215,48.871528,53.559028,Tyson Chicken Curry
4,20-21 LeBron James,82,30,1755,1286,495,1011,111,319,185,...,42,29,78,384,692,55.491329,34.796238,48.961424,54.451039,Tyson Chicken Curry
5,21-22 Matisse Thybulle,82,44,1712,378,144,322,46,155,44,...,139,82,148,98,167,58.682635,29.677419,44.720497,51.863354,Tyson Chicken Curry
6,17-18 Stephen Curry,82,33,1659,1341,469,938,208,500,195,...,81,9,95,261,438,59.589041,41.600000,50.000000,61.087420,Tyson Chicken Curry
7,20-21 Matisse Thybulle,82,36,1506,266,97,269,48,170,24,...,118,82,154,49,99,49.494949,28.235294,36.059480,44.981413,Tyson Chicken Curry
8,18-19 Tyson Chandler,80,0,792,165,67,108,0,3,31,...,15,14,78,67,105,63.809524,0.000000,62.037037,62.037037,Tyson Chicken Curry
9,22-23 Matisse Thybulle,82,2,638,164,58,128,24,69,24,...,62,18,66,34,59,57.627119,34.782609,45.312500,54.687500,Tyson Chicken Curry
10,10-11 Luke Walton,80,2,560,114,45,149,10,39,14,...,15,7,37,35,110,31.818182,25.641026,30.201342,33.557047,Tyson Chicken Curry
11,19-20 James Johnson,79,1,362,105,44,110,14,53,3,...,7,16,39,30,57,52.631579,26.415094,40.000000,46.363636,Tyson Chicken Curry

In [9]:
scdb = pd.read_csv(f'/Users/calebsmith/Library/Mobile Documents/com~apple~CloudDocs/Documents/What If/Hoops/Teams/SC&DB.csv')
scdb['Team'] = 'Serge Chewbacca Meets Dark Brandan'
scdb

,Name,GP,GS,Min,Pts,FGM,FGA,3PM,3PA,FTM,...,Stl,Blk,PF,2PM,2PA,2P%,3P%,FG%,eFG,Team
0,67-68 Wilt Chamberlain,82,82.0,3905.0,1832,821,1396,0,4,190,...,140,316,142,821,1392,58.979885,0.000000,58.810888,58.810888,Serge Chewbacca Meets Dark Brandan
1,11-12 Serge Ibaka,82,82.0,2273.0,787,346,687,0,3,95,...,48,292,207,346,684,50.584795,0.000000,50.363901,50.363901,Serge Chewbacca Meets Dark Brandan
2,20-21 Michael Porter,82,48.0,2222.0,1285,478,949,180,421,149,...,60,61,116,298,528,56.439394,42.755344,50.368809,59.852476,Serge Chewbacca Meets Dark Brandan
3,22-23 Stephen Curry,82,51.0,1974.0,1543,527,1137,258,634,231,...,65,29,119,269,503,53.479125,40.694006,46.350044,57.695690,Serge Chewbacca Meets Dark Brandan
4,93-94 Nate McMillan,82,67.0,1930.0,418,170,386,46,117,32,...,209,29,165,124,269,46.096654,39.316239,44.041451,50.000000,Serge Chewbacca Meets Dark Brandan
5,22-23 Michael Porter,82,31.0,1819.0,985,366,787,168,419,85,...,36,23,107,198,368,53.804348,40.095465,46.505718,57.179161,Serge Chewbacca Meets Dark Brandan
6,17-18 Stephen Curry,82,31.0,1646.0,1298,442,937,202,528,212,...,80,9,111,240,409,58.679707,38.257576,47.171825,57.950907,Serge Chewbacca Meets Dark Brandan
7,95-96 Nate McMillan,82,10.0,1288.0,297,111,298,49,145,26,...,96,27,113,62,153,40.522876,33.793103,37.248322,45.469799,Serge Chewbacca Meets Dark Brandan
8,09-10 DeShawn Stevenson,82,5.0,1011.0,136,47,203,14,103,28,...,29,4,76,33,100,33.000000,13.592233,23.152709,26.600985,Serge Chewbacca Meets Dark Brandan
9,12-13 Chris Andersen,82,0.0,632.0,254,98,172,4,6,54,...,19,36,72,94,166,56.626506,66.666667,56.976744,58.139535,Serge Chewbacca Meets Dark Brandan
10,14-15 Brandan Wright,80,0.0,503.0,244,112,167,0,1,20,...,19,33,45,112,166,67.469880,0.000000,67.065868,67.065868,Serge Chewbacca Meets Dark Brandan
11,20-21 Josh Hall,81,3.0,490.0,94,36,147,3,49,19,...,5,1,55,33,98,33.673469,6.122449,24.489796,25.510204,Serge Chewbacca Meets Dark Brandan

In [12]:
skfs = pd.read_csv(f'/Users/calebsmith/Library/Mobile Documents/com~apple~CloudDocs/Documents/What If/Hoops/Teams/SKFS.csv')
skfs['Team'] = 'Steve Kerrs Freak Show'
skfs

,Name,GP,GS,Min,Pts,FGM,FGA,3PM,3PA,FTM,...,Stl,Blk,PF,2PM,2PA,2P%,3P%,FG%,eFG,Team
0,18-19 Giannis Antetokounmpo,82,68.0,2405.0,1916,768,1366,45,198,335,...,91,90,233,723,1168,61.900685,22.727273,56.222548,57.869693,Steve Kerrs Freak Show
1,20-21 Giannis Antetokounmpo,82,53.0,2345.0,1827,738,1375,73,233,278,...,84,82,171,665,1142,58.231173,31.330472,53.672727,56.327273,Steve Kerrs Freak Show
2,21-22 Giannis Antetokounmpo,82,43.0,2254.0,1961,781,1436,66,228,333,...,89,82,176,715,1208,59.188742,28.947368,54.387187,56.685237,Steve Kerrs Freak Show
3,95-96 Steve Kerr,82,38.0,1967.0,666,236,513,116,248,78,...,80,1,98,120,265,45.283019,46.774194,46.003899,57.309942,Steve Kerrs Freak Show
4,21-22 Mitchell Robinson,82,51.0,1905.0,614,276,380,0,0,62,...,81,116,189,276,380,72.631579,0.000000,72.631579,72.631579,Steve Kerrs Freak Show
5,96-97 Steve Kerr,82,44.0,1901.0,664,253,510,107,239,51,...,79,6,95,146,271,53.874539,44.769874,49.607843,60.098039,Steve Kerrs Freak Show
6,19-20 Mitchell Robinson,82,31.0,1807.0,772,343,503,0,4,86,...,86,102,184,343,499,68.737475,0.000000,68.190855,68.190855,Steve Kerrs Freak Show
7,21-22 Matisse Thybulle,82,66.0,1724.0,411,165,342,47,155,34,...,148,66,142,118,187,63.101604,30.322581,48.245614,55.116959,Steve Kerrs Freak Show
8,20-21 Matisse Thybulle,82,16.0,1514.0,259,102,287,43,154,12,...,147,82,157,59,133,44.360902,27.922078,35.540070,43.031359,Steve Kerrs Freak Show
9,09-10 DeShawn Stevenson,82,0.0,927.0,130,44,209,16,109,26,...,19,6,63,28,100,28.000000,14.678899,21.052632,24.880383,Steve Kerrs Freak Show
10,80-81 John Duren,79,0.0,506.0,74,32,130,0,3,10,...,27,1,47,32,127,25.196850,0.000000,24.615385,24.615385,Steve Kerrs Freak Show
11,75-76 Lee Davis,75,0.0,426.0,53,17,108,0,0,19,...,10,7,88,17,108,15.740741,0.000000,15.740741,15.740741,Steve Kerrs Freak Show

In [13]:
bb = pd.read_csv(f'/Users/calebsmith/Library/Mobile Documents/com~apple~CloudDocs/Documents/What If/Hoops/Teams/BBGSW.csv')
bb['Team'] = 'Brick Brickowski'
bb

,Name,GP,GS,Min,Pts,FGM,FGA,3PM,3PA,FTM,...,Stl,Blk,PF,2PM,2PA,2P%,3P%,FG%,eFG,Team
0,72-73 Wilt Chamberlain,82,82.0,3607.0,1114,507,690,0,4,100,...,111,183,161,507,686,73.906706,0.000000,73.478261,73.478261,Brick Brickowski
1,17-18 Kevin Durant,82,56.0,2362.0,1813,679,1293,189,428,266,...,75,92,108,490,865,56.647399,44.158879,52.513534,59.822119,Brick Brickowski
2,20-21 Draymond Green,82,67.0,2292.0,560,217,484,40,144,86,...,144,61,201,177,340,52.058824,27.777778,44.834711,48.966942,Brick Brickowski
3,22-23 Stephen Curry,82,47.0,1972.0,1582,549,1104,272,610,212,...,53,22,82,277,494,56.072874,44.590164,49.728261,62.047101,Brick Brickowski
4,21-22 Kevon Looney,82,69.0,1762.0,487,214,431,0,1,59,...,59,39,172,214,430,49.767442,0.000000,49.651972,49.651972,Brick Brickowski
5,17-18 Stephen Curry,82,33.0,1658.0,1428,493,957,225,528,217,...,117,5,98,268,429,62.470862,42.613636,51.515152,63.270637,Brick Brickowski
6,18-19 Kevon Looney,82,12.0,1513.0,559,254,442,1,15,50,...,57,58,178,253,427,59.250585,6.666667,57.466063,57.579186,Brick Brickowski
7,22-23 Kevin Durant,81,24.0,1428.0,1130,436,789,79,198,179,...,36,56,79,357,591,60.406091,39.898990,55.259823,60.266160,Brick Brickowski
8,21-22 Draymond Green,82,14.0,1357.0,399,164,330,20,64,51,...,94,47,120,144,266,54.135338,31.250000,49.696970,52.727273,Brick Brickowski
9,08-09 Fabricio Oberto,79,2.0,769.0,166,72,175,0,6,22,...,13,10,72,72,169,42.603550,0.000000,41.142857,41.142857,Brick Brickowski
10,80-81 John Duren,72,2.0,579.0,101,45,157,0,1,11,...,30,3,59,45,156,28.846154,0.000000,28.662420,28.662420,Brick Brickowski
11,85-86 Frank Brickowski,62,2.0,397.0,96,36,88,1,1,23,...,22,6,72,35,87,40.229885,100.000000,40.909091,41.477273,Brick Brickowski

In [14]:
pj = pd.read_csv(f'/Users/calebsmith/Library/Mobile Documents/com~apple~CloudDocs/Documents/What If/Hoops/Teams/PJ.csv')
pj['Team'] = 'Peter Jackson'
pj

,Name,GP,GS,Min,Pts,FGM,FGA,3PM,3PA,FTM,...,Stl,Blk,PF,2PM,2PA,2P%,3P%,FG%,eFG,Team
0,78-79 Moses Malone,82,82.0,3499.0,1988,796,1534,15,57,381,...,69,102,176,781,1477,52.877454,26.315789,51.890482,52.379400,Peter Jackson
1,94-95 John Stockton,82,82.0,2930.0,1263,472,900,114,270,205,...,196,28,195,358,630,56.825397,42.222222,52.444444,58.777778,Peter Jackson
2,88-89 Dennis Rodman,82,73.0,2257.0,824,366,609,4,20,88,...,62,56,226,362,589,61.460102,20.000000,60.098522,60.426929,Peter Jackson
3,22-23 Stephen Curry,82,59.0,2000.0,1547,517,1096,265,603,248,...,53,8,107,252,493,51.115619,43.946932,47.171533,59.260949,Peter Jackson
4,21-22 Robert Covington,82,71.0,1983.0,612,211,515,128,326,62,...,117,95,176,83,189,43.915344,39.263804,40.970874,53.398058,Peter Jackson
5,17-18 Stephen Curry,82,23.0,1675.0,1198,419,891,195,482,165,...,65,5,91,224,409,54.767726,40.456432,47.025814,57.968575,Peter Jackson
6,18-19 Robert Covington,82,11.0,1236.0,403,137,361,73,210,56,...,55,31,98,64,151,42.384106,34.761905,37.950139,48.060942,Peter Jackson
7,22-23 Steven Adams,82,9.0,1161.0,438,197,354,0,4,44,...,45,30,79,197,350,56.285714,0.000000,55.649718,55.649718,Peter Jackson
8,09-10 DeShawn Stevenson,82,0.0,934.0,159,48,173,28,95,35,...,17,2,46,20,78,25.641026,29.473684,27.745665,35.838150,Peter Jackson
9,22-23 Andre Drummond,82,0.0,901.0,456,202,351,1,2,51,...,45,38,100,201,349,57.593123,50.000000,57.549858,57.692308,Peter Jackson
10,14-15 Rajon Rondo,82,0.0,727.0,209,93,237,11,42,12,...,43,2,33,82,195,42.051282,26.190476,39.240506,41.561181,Peter Jackson
11,20-21 Josh Hall,79,0.0,423.0,122,51,158,6,50,14,...,4,1,37,45,108,41.666667,12.000000,32.278481,34.177215,Peter Jackson

In [15]:
all_seasons = pd.concat([aad, aotc2, iwi, mj, tcc, scdb, skfs, bb, pj])
all_seasons

,Name,GP,GS,Min,Pts,FGM,FGA,3PM,3PA,FTM,...,Stl,Blk,PF,2PM,2PA,2P%,3P%,FG%,eFG,Team
0,15-16 DeAndre Jordan,82,82.0,2676.0,1198,538,786,1,3,121,...,48,174,181,537,783,68.582375,33.333333,68.447837,68.511450,Andre and Deandre
1,95-96 Dennis Rodman,82,77.0,2169.0,437,192,390,5,33,48,...,49,28,184,187,357,52.380952,15.151515,49.230769,49.871795,Andre and Deandre
2,18-19 LeBron James,82,54.0,1996.0,1355,547,1124,102,305,159,...,73,29,94,445,819,54.334554,33.442623,48.665480,53.202847,Andre and Deandre
3,22-23 Stephen Curry,82,61.0,1992.0,1523,527,1166,254,657,215,...,63,19,104,273,509,53.634578,38.660578,45.197256,56.089194,Andre and Deandre
4,93-94 Nate McMillan,82,79.0,1962.0,419,171,437,47,136,30,...,241,25,186,124,301,41.196013,34.558824,39.130435,44.508009,Andre and Deandre
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,22-23 Steven Adams,82,9.0,1161.0,438,197,354,0,4,44,...,45,30,79,197,350,56.285714,0.000000,55.649718,55.649718,Peter Jackson
8,09-10 DeShawn Stevenson,82,0.0,934.0,159,48,173,28,95,35,...,17,2,46,20,78,25.641026,29.473684,27.745665,35.838150,Peter Jackson
9,22-23 Andre Drummond,82,0.0,901.0,456,202,351,1,2,51,...,45,38,100,201,349,57.593123,50.000000,57.549858,57.692308,Peter Jackson
10,14-15 Rajon Rondo,82,0.0,727.0,209,93,237,11,42,12,...,43,2,33,82,195,42.051282,26.190476,39.240506,41.561181,Peter Jackson
11,20-21 Josh Hall,79,0.0,423.0,122,51,158,6,50,14,...,4,1,37,45,108,41.666667,12.000000,32.278481,34.177215,Peter Jackson

# Analysis

In [16]:
all_seasons['PPM'] = all_seasons['Pts'] / all_seasons['Min']
all_seasons['ORPM'] = all_seasons['OReb'] / all_seasons['Min']
all_seasons['RPM'] = all_seasons['Reb'] / all_seasons['Min']
all_seasons['APM'] = all_seasons['Ast'] / all_seasons['Min']
all_seasons['BPM'] = all_seasons['Blk'] / all_seasons['Min']
all_seasons['SPM'] = all_seasons['Stl'] / all_seasons['Min']

In [17]:
all_seasons.columns

Index(['Name', 'GP', 'GS', 'Min', 'Pts', 'FGM', 'FGA', '3PM', '3PA', 'FTM',
       'FTA', 'OReb', 'Reb', 'Ast', 'TO', 'Stl', 'Blk', 'PF', '2PM', '2PA',
       '2P%', '3P%', 'FG%', 'eFG', 'Team', 'PPM', 'ORPM', 'RPM', 'APM', 'BPM',
       'SPM'],
      dtype='object')

In [18]:
all_seasons.sort_values('PPM', ascending = False).head(10)

,Name,GP,GS,Min,Pts,FGM,FGA,3PM,3PA,FTM,...,3P%,FG%,eFG,Team,PPM,ORPM,RPM,APM,BPM,SPM
2,21-22 Giannis Antetokounmpo,82,43.0,2254.0,1961,781,1436,66,228,333,...,28.947368,54.387187,56.685237,Steve Kerrs Freak Show,0.870009,0.039929,0.305679,0.200089,0.036380,0.039485
5,17-18 Stephen Curry,82,33.0,1658.0,1428,493,957,225,528,217,...,42.613636,51.515152,63.270637,Brick Brickowski,0.861279,0.014475,0.118818,0.154403,0.003016,0.070567
6,17-18 Stephen Curry,82,21.0,1680.0,1389,460,925,238,530,231,...,44.905660,49.729730,62.594595,Andre and Deandre,0.826786,0.016071,0.124405,0.180357,0.004762,0.054167
2,22-23 Stephen Curry,82,49.0,1986.0,1635,577,1186,270,629,211,...,42.925278,48.650927,60.033727,Tyson Chicken Curry,0.823263,0.011078,0.134441,0.172205,0.012588,0.028701
7,17-18 Stephen Curry,82,34.0,1673.0,1372,482,987,234,541,174,...,43.253235,48.834853,60.688956,Attack of the Clones: Part 2,0.820084,0.026898,0.123730,0.191273,0.004184,0.057382
0,87-88 Michael Jordan,82,82.0,3419.0,2775,1127,2209,5,69,516,...,7.246377,51.018560,51.131734,Can Michael Win a WIS Championship?,0.811641,0.030126,0.113191,0.147119,0.044165,0.089792
6,17-18 Stephen Curry,82,33.0,1659.0,1341,469,938,208,500,195,...,41.600000,50.000000,61.087420,Tyson Chicken Curry,0.808318,0.023508,0.134418,0.157926,0.005425,0.048825
2,22-23 Stephen Curry,82,48.0,1989.0,1598,548,1146,265,615,237,...,43.089431,47.818499,59.380454,Attack of the Clones: Part 2,0.803419,0.013575,0.125691,0.195073,0.007039,0.029160
3,22-23 Stephen Curry,82,47.0,1972.0,1582,549,1104,272,610,212,...,44.590164,49.728261,62.047101,Brick Brickowski,0.802231,0.013692,0.145538,0.163286,0.011156,0.026876
0,18-19 Giannis Antetokounmpo,82,68.0,2405.0,1916,768,1366,45,198,335,...,22.727273,56.222548,57.869693,Steve Kerrs Freak Show,0.796674,0.049064,0.293139,0.193347,0.037422,0.037838